services:
  - type: web
    name: bnbconnect
    runtime: node
    buildCommand: |
      yarn install
      cd client
      yarn install
      CI=false yarn build
      cd ..
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 16.20.2 