// Booking action types
export const SET_BOOKING_DATES = "SET_BOOKING_DATES";
export const SET_LOCATION = "SET_LOCATION";
export const INCREMENT_ADULTS_NUMBER = "INCREMENT_ADULTS_NUMBER";
export const DECREMENT_ADULTS_NUMBER = "DECREMENT_ADULTS_NUMBER";
export const INCREMENT_CHILDREN_NUMBER = "INCREMENT_CHILDREN_NUMBER";
export const DECREMENT_CHILDREN_NUMBER = "DECREMENT_CHILDREN_NUMBER";
export const INCREMENT_INFANTS_NUMBER = "INCREMENT_INFANTS_NUMBER";
export const DECREMENT_INFANTS_NUMBER = "DECREMENT_INFANTS_NUMBER";
export const RESET_GUESTS_NUMBER = "RESET_GUESTS_NUMBER";
export const TOGGLE_GUEST = "TOGGLE_GUEST";
export const TOGGLE_LOCATION_SEARCH = "TOGGLE_LOCATION_SEARCH";
// export const TOGGLE_DATE_PICKER = "TOGGLE_DATE_PICKER";
export const RESET_TOGGLE = "RESET_TOGGLE";
export const TOGGLE_CHECK_IN = "TOGGLE_CHECK_IN";
export const TOGGLE_CHECK_OUT = "TOGGLE_CHECK_OUT";
export const LOAD_RECOMMENDED_LOCATION_RESULTS =
  "LOAD_RECOMMENDED_LOCATION_RESULTS";

// listing action types
export const TOGGLE_ISFETCHING = "TOGGLE_ISFETCHING";
export const SET_LISTINGS = "SET_LISTINGS";
export const SET_FILTERED_LISTINGS = "SET_FILTERED_LISTINGS";
export const SET_CURRENT_LISTING = "SET_CURRENT_LISTING";
export const CLEAR_CURRENT_LISTING = "CLEAR_CURRENT_LISTING";
export const SET_ERROR_LISTING = "SET_ERROR_LISTING";
export const CLEAR_ERROR_LISTING = "CLEAR_ERROR_LISTING";

// User action types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGOUT_ERROR = "SIGN_OUT_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const AUTH_ERROR = "AUTH_ERROR";

// alert action types
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// User Booking Types
export const LOAD_BOOKINGS_LISTINGS = "LOAD_BOOKINGS_LISTINGS";
export const REMOVE_BOOKING_LISTING = "REMOVE_BOOKING_LISTING";
export const CLEAR_BOOKING_LISTING = "CLEAR_BOOKING_LISTING";
export const LOAD_BOOKINGS = "LOAD_BOOKINGS";
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const REMOVE_BOOKING = "REMOVE_BOOKING";
export const REMOVE_ALL_BOOKINGS = "REMOVE_ALL_BOOKINGS";
export const SET_USER_BOOKING_ERROR = "SET_USER_BOOKING_ERROR";
export const CLEAR_USER_BOOKING_ERRORS = "CLEAR_USER_BOOKING_ERRORS";

// review Types
export const LOAD_REVIEWS = "LOAD_REVIEWS";
export const LOAD_ALL_REVIEWS = "LOAD_ALL_REVIEWS";
export const LOAD_CURRENT_REVIEW = "LOAD_CURRENT_REVIEW";
export const SET_CURRENT_REVIEW = "SET_CURRENT_REVIEW";
export const SET_IS_REVIEWED = "SET_IS_REVIEWED";
export const CLEAR_CURRENT_REVIEW = "CLEAR_CURRENT_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const REMOVE_REVIEW = "REMOVE_REVIEW";
// export const CLEAR_REVIEW = "CLEAR_REVIEW";
export const SET_ERROR_REVIEW = "SET_ERROR_REVIEW";
export const CLEAR_ERROR_REVIEW = "CLEAR_ERROR_REVIEW";
