// Booking action types
export const SET_BOOKING_DATES = "SET_BOOKING_DATES";
export const SET_LOCATION = "SET_LOCATION";
export const INCREMENT_ADULTS_NUMBER = "INCREMENT_ADULTS_NUMBER";
export const DECREMENT_ADULTS_NUMBER = "DECREMENT_ADULTS_NUMBER";
export const INCREMENT_CHILDREN_NUMBER = "INCREMENT_CHILDREN_NUMBER";
export const DECREMENT_CHILDREN_NUMBER = "DECREMENT_CHILDREN_NUMBER";
export const INCREMENT_INFANTS_NUMBER = "INCREMENT_INFANTS_NUMBER";
export const DECREMENT_INFANTS_NUMBER = "DECREMENT_INFANTS_NUMBER";
export const RESET_GUESTS_NUMBER = "RESET_GUESTS_NUMBER";
export const TOGGLE_GUEST = "TOGGLE_GUEST";
export const TOGGLE_LOCATION_SEARCH = "TOGGLE_LOCATION_SEARCH";
export const TOGGLE_DATE_PICKER = "TOGGLE_DATE_PICKER";
export const RESET_TOGGLE = "RESET_TOGGLE";
export const TOGGLE_CHECK_IN = "TOGGLE_CHECK_IN";
export const TOGGLE_CHECK_OUT = "TOGGLE_CHECK_OUT";
export const LOAD_RECOMMENDED_LOCATION_RESULTS =
  "LOAD_RECOMMENDED_LOCATION_RESULTS";

// listing action types
export const TOGGLE_ISFETCHING = "TOGGLE_ISFETCHING";
export const SET_LISTINGS = "SET_LISTINGS";
export const SET_FILTERED_LISTINGS = "SET_FILTERED_LISTINGS";

// User action types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGOUT_ERROR = "SIGN_OUT_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const AUTH_ERROR = "AUTH_ERROR";

// alert action types
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
